# Site settings
title: Your awesome title
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
   Blog dedicado a la programación de juegos de estrategia en Java. Desde la representación del mapa mediante
   coordenadas hexagonales hasta la creación de algoritmos de pathfinding e inteligencia artificial.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
