# Site settings
title: De Ludo Bellico
email: magomar@gmail.com
description: > # this means to ignore newlines until "baseurl:"
   Blog dedicado a la programación de juegos de estrategia en Java. Desde la representación del mapa mediante
   coordenadas hexagonales hasta la creación de algoritmos de pathfinding e inteligencia artificial.
baseurl: "/deludobellico/" # the subpath of your site, e.g. /blog/
url: "http://magomar.github.io" # the base hostname & protocol for your site
twitter_username: magomarX
github_username:  magomar

# Build settings
markdown: kramdown
