# Site settings
title: De Ludo Bellico
email: magomar@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Programming wargames in Java.
baseurl: "/deludobellico" # the subpath of your site, e.g. /blog/
url: "http://magomar.github.io" # the base hostname & protocol for your site
twitter_username: magomarX
github_username:  magomar

# Build settings
markdown: kramdown

safe: true
lsi: false
source: .

permalink: pretty
#pygments: true